### ISSUE TITLE
is this ready to work?

### ISSUE THREAD

**Issue by SeekPoint** [ShubhangDesai/tf-lstm-stock-market#1]
any guide to get start

**Comment by ShubhangDesai** [comment]
Hi loveJasmine! There model is essentially working. There are just a couple of things that I'd add to make it even better:
1) Instead of having an the input take 30 vectors, I'd have it take 31 while training, produce 30 predicitons from the 1st vector, and then check _only_ against the 31st. In other words, the MSE is dependent only on the 31st vector. This will also mean that there will be some recoding necessary to produce yT once it's trained.
2) This is an easy one: learning rate decay. I haven't implemented it, and I've noticed that, even though the descent never diverges, it sometimes fails to coverge because the constant learing rate keeps overshooting local minima.

I'll add these features eventually, but if you're too anxious to wait, feel free to fork my repo and do it yourself!
